### ISSUE TITLE
Suspicious changeset in Colombia

### ISSUE THREAD

**Issue by risturiz** [OSMLatam/pow#2]
https://osmcha.org/changesets/126200911/

P.D. Reporte realizado por @erickdeoliveiraleal en el canal Telegram de Colombia

**Comment by risturiz** [comment]
Usuario: https://www.openstreetmap.org/user/chitiva/

Tiene 2 changesets ( 126151762 / 126200911 ) donde se observa eliminación de objetos que pueden ser facilmente verificados en la imagen satelital:

#126151762:

![changeset126151762-osmcha](https://user-images.githubusercontent.com/12375/192824735-8bda9004-01a2-46db-acfc-b6fd43019404.png)

#126200911: 

![changeset126200911-osmcha](https://user-images.githubusercontent.com/12375/192823220-bbb6a76c-72a7-477a-b79b-6f756d80aad7.png)


- [x] Se procede a contactar al usuario mediante "Discussion" con la URL del issue ( tiempo prudencial para que responda o repare los errores? )
- [ ] Verificación que los errores fueron corregidos
- [ ] Se cierra el issue?

**P.D. Esto es una prueba de reporte para poder hacer seguimiento de una forma más pública y con mejor control de notificaciones/recordatorios**

**Comment by angoca** [comment]
Este reporte lo creó: @erickdeoliveiraleal

**Comment by risturiz** [comment]
Parece que el bot de recordatorio falló miserablemente xD ... Voy a revisar una alternativa

**Comment by risturiz** [comment]
Changeset [#126151762](https://www.openstreetmap.org/changeset/126151762):

- Se trata de revertir usando el plugin de Josm [Reverter](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Reverter)

![changeset-revert-126151762](https://user-images.githubusercontent.com/12375/194767624-781a8c5a-ae4e-4a2e-b8f7-047eedafdb55.png)

- Errores generados con MapWithAI: Routing Islands

- Se procede a resolver usando Strava:

![Screenshot_20221009_111913](https://user-images.githubusercontent.com/12375/194767890-a5f39001-4018-489d-a252-f90aa17908ad.png)

**Comment by risturiz** [comment]
Btw, @angoca me puedes ayudar con el changeset [#126200911](https://www.openstreetmap.org/changeset/126200911) ? :-)

**Comment by angoca** [comment]
A reversarlo? Nunca he usado el plugin, vamos a ver cómo me va.

**Comment by risturiz** [comment]
> A reversarlo? Nunca he usado el plugin, vamos a ver cómo me va.

Sólo para efectos de no ser el único dictador revirtiendo cambios xD

**Comment by angoca** [comment]
Qué comentario usaste?
Yo este:

Revertido 126200911 https://github.com/OSMLatam/pow/issues/2

**Comment by risturiz** [comment]
> Qué comentario usaste? Yo este:
> 
> Revertido 126200911 #2

Revert and Fixed Changeset 126151762 https://github.com/OSMLatam/pow/issues/2 #CO #POW
