### ISSUE TITLE
casas todas iguales, numeradas, sin correspondencia con fotos.

### ISSUE THREAD

**Issue by mfrasca** [OSMLatam/pow#4]
Mirabella Park.

En este conjunto, y los pocos antes y después, está distribuida un "insert" de casas de un conjunto residencial, todas numeradas, y 
1) no se entiende de dónde sale la información numérica.
2) ninguna de las casas corresponde con lo que se puede apreciar en las fotos.

https://www.openstreetmap.org/changeset/62706557

País: Panamá (provincia: Chiriquí)

este es nada más un ejemplo de lo típico mapeado por el mismo autor.
todo el centro de David fue llenado en el mismo estilo, y lo he estado limpiando poco a la vez.
https://forum.openstreetmap.org/viewtopic.php?id=73759

Creator: https://www.openstreetmap.org/user/Alvarado2510/ (Mapper since:  December 06, 2017)

![changeset62706557-osmcha](https://user-images.githubusercontent.com/12375/193430977-63da6991-91d5-4e16-be21-578ffb5e5eaf.png)

**Comment by risturiz** [comment]
Usó Bing Imagery hace 4 años y todavian no aparecen esas edificaciones en la imagen satelital? Quizás era un proyecto urbanistico que nunca se concretó? Yo creo que si no responde en un tiempo prudencial se puede hacer revert?... Que opinan?

**Comment by angoca** [comment]
Después de ver la imagen de Google Maps, se ve lo mismo que la de Bing.

La de EOx, si bien la resolución es muy baja pero es reciente, tiene las mismas áreas de color de Bing y Google.

Por otro lado, el mapeo de casas es muy bien definido, pero las casas realmente parece que tienen/van a tener otra forma.

En mi opinión, como dice Rafa, parece que se hubiera tomado del proyecto inmobiliario, pero no está completo.
Revisando el proyecto en Internet, veo la página de Facebook https://www.facebook.com/MirabellaPark que está desde 2013. Entonces, tiene casi 10 años, y es raro que esté tan incompleto.

En contraste, hay mucha otras casas alrededor que no están mapeadas.

Preguntar de dónde se sacaron esas formas de casas. Igualmente, revisar si esas casas tienen alguna etiqueta adicional, como Starting_date o construction. De manera que se sobreentienda que no es lo actual, sino futuro.

**Comment by risturiz** [comment]
> En mi opinión, como dice Rafa, parece que se hubiera tomado del proyecto inmobiliario, pero no está completo.
> Revisando el proyecto en Internet, veo la página de Facebook https://www.facebook.com/MirabellaPark que está desde 2013. Entonces, tiene casi 10 años, y es raro que esté tan incompleto.

Pero creo que lo comentamos en el Notathon reciente, sobre el histórico... Tiene sentido mapear algo a futuro?... Por cierto @mfrasca como haces para detectar esto? Monitoreo? porque digamos que seria una edición "normal". No existe alguien mas de Panamá que pudiese mirar la zona? o tenga un conocimiento adicional?

**Comment by mfrasca** [comment]
Cómo hago para detectar estas invenciones … pues sí monitoreando el país. 

En el historial de Firefox tengo [este enlace](https://www.openstreetmap.org/history#map=8/8.455/-80.105) y lo abro con regularidad. Me resulta más sencillo que abrir una query OSMcha. En el país raras veces hay más que 4 editores activos en un día, y somos siempre los mismos. (La herramienta welcome.osm.be no evidencia las ediciones de maperos "antiguos" que vuelven a mapear.)

Esta edición es una edición "normal", cierto, y entra en una categoría que llamaría "Casas Alvarado2510", como me atreví a hacerlo en la descripción de [este conjunto de cambios](https://www.openstreetmap.org/changeset/106605645). Mucho de David centro fue mapeado de esta forma en una serie muy larga de conjuntos de cambios rapidísimos, en pocos días. Tan sólo por ejemplo los conjuntos de cambios [82313971](https://www.openstreetmap.org/changeset/82313971), [82314296](https://www.openstreetmap.org/changeset/82314296), [82314390](https://www.openstreetmap.org/changeset/82314390), [82359743](https://www.openstreetmap.org/changeset/82359743) (foto abajo), pero son decenas y decenas de conjuntos así.

![image](https://user-images.githubusercontent.com/122869/193461435-6dfb1bf8-f64f-43f3-9c05-366fa9c2284e.png)

Estaba mirando otra cosa, si encontraba un área con edificios AI de Microsoft, y me llamó la atención esa barriada sin área residencial, por eso revisé. La estructura era la típica del copia-pega sin pensarlo, y al abrirlo en JOSM me enteré que no tenía relación con la realidad. De haber sido otro día, lo habría dejado así, pero acababa de ver esta vuestra iniciativa, y pensé de proponerle el caso.

Si existe alguien más de Panamá en la zona? Ustedes están en contacto con Carlos Eduardo, en su grupo se encuentran tanto Alvarado2510 como JonathanQuiel24, ambos de Chiriquí. A mi no me contestan. A veces sugiero a Rick Morales de tomar trazas cuando él pase por ahí, pero él hace senderismo, no tiene interés en las urbanizaciones.

**Comment by risturiz** [comment]
Excelente @mfrasca !! Gracias por ampliar la información... A mi realmente me parecen super interesantes estos temas y que ahora puedan quedar documentados para buscar una solución en conjunto le añade valor... Por lo visto entonces yo mi inclinaria hacia importación masiva de edificios en estos casos.

Al menos en Panamá existe alguien monitoreando esto... Quien sabe cuantos erorres de este tipo existen en otros paises y ni nos enteramos.

**Comment by risturiz** [comment]
JA! Buena documentación que estás desarrollando acá @mfrasca :-) ... La semana que pasó estuve limitado de tiempo, pero la única manera que veo es alguien de la zona pueda corroborar esa información para tener una prueba real y no solamente la imagen satelital.

**Comment by mfrasca** [comment]
hola a todos. veo que Alvarado2510 escribe en los dos grupos Telegram [OSMLatam](https://t.me/OSMLatam/38812) y [OpenStreetMap Panama](https://t.me/OpenstreetmapPanama/1308), y que los invitaron a argumentar aquí sus contribuciones a la base de datos.

También veo que pensó [mejorar la situación](https://www.openstreetmap.org/changeset/127258917) en la urbanización Mirabella Park. Me deja perplejo el comentario a su conjunto de cambios (Buenos días procedi a eliminar las casas que aun no se aprecian en las imagnes que tenemos como fuente, aunque ya exista, esperare unos años, para que nos las actualices.), seguramente no lo entendí bien, pero lo que entiendo yo es que lo mapeado originariamente existe, que nos hace el favor de quitar lo que no resulta en las fotos aéreas todavía desactualizadas, y que ojalá estas serán puestas al día pronto. Asumiendo buena fe, sería útil tener una grabación con Mapillary o KartaView o unas notas fotográficas con StreetComplete.

**Comment by mfrasca** [comment]
siempre a propósito de "cuál es la fuente de los números de las casas", 

la [casa sin número](https://www.openstreetmap.org/way/989734781) está frente a la número 188 y al lado de la 189. igual a la calle siguiente [casa sin número](https://www.openstreetmap.org/way/989734778) frente a la 174, al lado de la 175. 

la numeración de 140 a 163 tiene un hueco de dos números pero con tres casas. https://www.openstreetmap.org/way/989734782

la numeración de las calles en la zona es 5a, Avenida B, 6a, 7a.

**Comment by angoca** [comment]
> Cómo hago para detectar estas invenciones … pues sí monitoreando el país.
> 
> En el historial de Firefox tengo [este enlace](https://www.openstreetmap.org/history#map=8/8.455/-80.105) y lo abro con regularidad. Me resulta más sencillo que abrir una query OSMcha. En el país raras veces hay más que 4 editores activos en un día, y somos siempre los mismos. (La herramienta welcome.osm.be no evidencia las ediciones de maperos "antiguos" que vuelven a mapear.)
> 
> Esta edición es una edición "normal", cierto, y entra en una categoría que llamaría "Casas Alvarado2510", como me atreví a hacerlo en la descripción de [este conjunto de cambios](https://www.openstreetmap.org/changeset/106605645). Mucho de David centro fue mapeado de esta forma en una serie muy larga de conjuntos de cambios rapidísimos, en pocos días. Tan sólo por ejemplo los conjuntos de cambios [82313971](https://www.openstreetmap.org/changeset/82313971), [82314296](https://www.openstreetmap.org/changeset/82314296), [82314390](https://www.openstreetmap.org/changeset/82314390), [82359743](https://www.openstreetmap.org/changeset/82359743) (foto abajo), pero son decenas y decenas de conjuntos así.
> 
> ![image](https://user-images.githubusercontent.com/122869/193461435-6dfb1bf8-f64f-43f3-9c05-366fa9c2284e.png)
> 
> Estaba mirando otra cosa, si encontraba un área con edificios AI de Microsoft, y me llamó la atención esa barriada sin área residencial, por eso revisé. La estructura era la típica del copia-pega sin pensarlo, y al abrirlo en JOSM me enteré que no tenía relación con la realidad. De haber sido otro día, lo habría dejado así, pero acababa de ver esta vuestra iniciativa, y pensé de proponerle el caso.
> 
> Si existe alguien más de Panamá en la zona? Ustedes están en contacto con Carlos Eduardo, en su grupo se encuentran tanto Alvarado2510 como JonathanQuiel24, ambos de Chiriquí. A mi no me contestan. A veces sugiero a Rick Morales de tomar trazas cuando él pase por ahí, pero él hace senderismo, no tiene interés en las urbanizaciones.

Realmente la silueta y giro de las casas que muestras en la imagen, todas tienen la misma forma y orientación. Esto parece ser producto de un copiado y pegado masivo, sin tener presente la silueta de las construcciones (casas). Le recomendaría a Alvarado2510 que revise las fotos satelitales disponibles (Bing, Maxar) y solo para comparar la de Google. Igualmente, rectificar el desaface (offset), y adecuar las construcciones con respecto a lo que se ve.

**Comment by risturiz** [comment]
Hasta donde entiendo Alvarado2510 ha ido reparando algunos cambios... Seria ideal que pudiese documentarlos acá para que todo eso quede como historico luego.

**Comment by mfrasca** [comment]
Es cierto, Alvarado2510 ha ido arreglando cosas para que se vean mejor. pero sigue sin respuesta la inquietud: de dónde sale la información numérica? por ejemplo los cinco lotes mapeados como cinco casas cuadradas iguales numeradas de 06 a 10, mientras la foto aérea muestra cuatro lotes y cuatro casas rectangulares de tres formas diferentes. 
https://www.openstreetmap.org/way/822398262

**Comment by mfrasca** [comment]
no fue fácil, pero encontré el mapa del Mirabella Park.
https://www.inmopanama.com/files/props/16132/fde6eac8cff43d089b0f755f12ebe4f9.jpg
es bien detallado!
![mirabella-park](https://user-images.githubusercontent.com/122869/195462118-eb2d08c4-e516-4ba2-b974-570832a9f4a0.jpg)

**Comment by alvarado2510** [comment]
Saludos buenas noches, mi nombre es Luis, son el editor alvarado2510, lamento no haber respondido antes.

El proyecto Mirabella Park, inicio su construcción hace más de 2 años, cuando lo edite, solo estaba en planes, por eso encontraron mi edición en ese estado.
Lamentablemente la imagen aérea actual es del enero 2020 en la provincia de Chiriquí, mi error fue haberme adelantado a lo que es hoy en realidad.
Pueden comparar los residenciales de los alrededores, podrán notar que ya no edito, ni sus calles, ni sus casa, aunque hoy en día existan, yo cambien mi forma de editar los residenciales, porque nos toca trabajar con imágenes aéreas de más de 2 años de retraso, yo esperare como 5 años más para entonces llevar mi conocimiento local a OSM.
Hace 1 año aproximadamente, me estaba apoyando con mapillary, si se toman la molestia verán que el 35% del distrito de David, tiene fotos mías, pero me desanime, ya que me difuminaron las foto principales que necesitaba como fuente, para responder otro temas que tengo con los nombre de algunas calles en el distrito.
Ya yo modifique Mirabella Park a enero del 2020, por mi parte lo dejare así, me disculpo, mi intención fue en su momento presentar un mapa digital más cerca de la realidad, le di uso a esas ediciones, para evitar borrar el trabajo.
Espero haber sido claro, con el tema del residencial, si alguien tiene dudas, con gusto responderé.

**Comment by mfrasca** [comment]
> El proyecto Mirabella Park, inicio su construcción hace más de 2 años, cuando lo edite, solo estaba en planes, por eso encontraron mi edición en ese estado.

Luis @alvarado2510, tienes acceso a los planes? o cómo sabes los números de los lotes?
la misma pregunta te la vuelvo a hacer para todos los demás puntos del mapa en que has ido añadiendo casas numeradas (todas iguales, sin correspondencia con las fotos), mencionando como fuente Bing, o Maxar, o Esri, y cada vez que contestaste, nos mencionas las diferencias entre las fotos, o su antigüedad, o sus errores de alineamiento. Pero nunca nos dijiste si tienes acceso a los planes o cómo sabes los números de los lotes.

Como ves, Rafael @risturiz al ver las fotos de los planes, enseguida me pregunta sobre la licencia. Si ya sabes que son planes sin licencia de copia, entonces lo digas por favor, sin miedo a que te se vuelva a decir "no copies", eso ya lo has escuchado. Si tienes manera de recibir los planes libres de licencia (público dominio) de ahí podemos seguir.

El otro punto que menciona Luis es sobre [su decepción con Mapillary](https://t.me/OpenstreetmapPanama/1153) (La verdad me desanime, porque me difuminaron en las fotos exactamente donde esta el letrero.). Una alternativa menos propietaria a Mapillary es KartaView (Esa te [la mencionó Jorge Aguirre](https://t.me/OpenstreetmapPanama/1163) en respuesta a tu mensaje, y la [sugerí yo a Carlos Eduardo](https://t.me/Comunidad_OSM_Panama/11315)). Además, hay otras maneras de subir notas fotográficas a OSM, por ejemplo con StreetComplete. Las notas fotográficas subidas con StreetComplete nadie te las edita. StreetComplete no aparece mencionado nunca en tu grupo, pero sí 12 veces en el grupo de que se salieron con Carlos Eduardo, la primera vez el 6 de septiembre del 2019.

Sin considerar el problema de las fuentes, mapear números de lotes está muy bien, pero no se hace como lo haces tú. Si una casa no existe, no la mapees tan solo para tener un objeto a que asociar el número de lote. Los lotes tienen su [etiqueta dedicada](https://wiki.openstreetmap.org/wiki/ES:Tag:place%3Dplot), y al objeto lote le pones en número.

**Comment by alvarado2510** [comment]
Buenos días a todos, buenos dias @mfrasca gracias por tus comentario, donde vivo esa muy común la publicad, en las calles de nuevo proyectos, mucho antes de su construcción, se que tengo foto de cuando Mirabella Park, no la encontrado entretantos cosas que recopilo.
Aquí un ejemplo publicitario de otro residencial: https://photos.app.goo.gl/csCKkjiq8WcoJSSi9
No se de que países son, quizás las practicas de dirección no sean iguales, pero acá en Panamá se acostumbra a identificar las casas o edificios con un numero, déjeme buscar otro ejemplo.

Aquí esta un ejemplo: https://www.mapillary.com/app/?pKey=498885421502722
como pueden ver en la foto además de difuminado el nombre de la calle también el numero de la casa, esa casa debe tener mas de 40 años, yo tengo 44 años viviendo en el distrito de David, ahora volviendo al tema de Mirabella Park, en su momento se recopile información del mismo, viendo las imágenes que compartió @mfrasca me parece haberle visto, pero sin colores.

**Comment by alvarado2510** [comment]
Por ejemplo la casa donde vivo, la constructora coloco los numero de las casa en el medidor de corriente eléctrica, en Panamá se exige colocar el medidor de corriente en un punto accesible para la persona que mensualmente toma la lectura del mismo, así como esta en donde vivo lo note en otros proyectos, si comparas la imagen que compartiste de Mirabella Park, veras que además de los números de las casa, también esta el de las calles, ahora si no se puede usas esa imagen como fuente, por favor me gustaría saberlo.

Les voy a dejar una anécdota personal, mi abuela murió hace 4 años con 99 años de edad, mi mamá desde entonces me pidió visitar la casa de mi abuela de forma periódica ya que esta deshabitada, la casa que era de mi abuela tiene el numero 54 afuera, en ese residencial yo puedo decir que tiene el 95% de los numero de las casa, totalmente visible desde la calle, al igual que Mirabella Park, su numero asignado cada uno, mi madre me informo que mi abuela vivió mas de 40 años en esa casa, así que concluyo que el uso de los numero residenciales en Panamá se practica desde hace mucho, cuidado que desde el siglo XIX.

Renunciare a mapillary, usare StreetComplety ya que me lo recomendaron, espero que me ayude para responder los cientos de correos que tengo pendientes, @mfrasca te pido tengas paciencia para con las respuesta pendiste, a los miles de casos como Mirabella Park, para aclarar.

En el grupo que estoy de OSM, nos facilitaron el año pasado una herramienta "ispector", algo así, muy buen creo que es la que usa @mfrasca para detectar mis errores, allí encontré la cantidad de cosas que edite y que a la fechas están incompletas.
Por ejemplo descubrí que el numero de las casa va ligado en OSM con el nombre de la calle, por esos me detuve seguir editando casa con numero, hasta corregir todas las anteriores.
Por ejemplo tengo la foto de todas las casas del residencial "Quinta de La Riviera", pero no se las coloco, por que no tengo los nombre de las calles del residencial, ese residencial lo tengo pendiente, en ese punto, hasta tener la información completa y así llevarla a OSM.

**Comment by alvarado2510** [comment]
Quiero salirme del tema un poco, voy aprovecha la robusta documentación de @mfrasca , como puede ver en la distintas fotos, podrán ver el desajuste de la imagen de Maxar, el año pasado si no me equivoco nos facilitaron esta imágenes, mucho mas actualizadas que la de Bing y Esri que son por ejemplo las que usaba antes, no se si ustedes lo notaron pero la imagen de maxar no se ajusta a la realidad, encontré un video en youtube, que explica como solicitar ese ajuste, pero no lo hice, por me imagine que se añadiera a mi bandeja de entrada otro correo mas, cuestionando ese ajuste.
Les voy a contar como lo detecte, el año pasado ajuste calles en David con la imagen aérea de maxar, soy usuario de OsmAnd, cuando lo uso ahora que se actualizaron los cambio en OSM, me brinca entre las calles paralelas, ya que mi gps circula por en medio de ellas, y el app trata de ubicarme de forma magnética en una de ellas, si notan mis tacks o mis recorrido en Mapillary, podrán notar también el desajuste, si alguien aquí puede ayudarme con ellos, lo agradezco.

**Comment by alvarado2510** [comment]
Mirabella Park como comente desde un principio, lo modifique, creo que ya hasta fue validado, lo lleve al 2020, por ahora lo dejare así, hasta podre evidenciar su actualidad al 2022 o los años que Dios me permita seguir editando, cuando estuve en le grupo de @mfrasca yo comente muchas veces el tema de la desactualización de las fotografías aéreas, por ejemplo Bing que era la que usábamos en aquel entonces.

**Comment by mfrasca** [comment]
> comente muchas veces el tema de la desactualización de las fotografías aéreas

Es cierto, nos has comentado varias veces de los problemas de los alineamientos de las fotos, y de cuanto son desactualizadas. Sin embargo, 
- validar la edad de las fotos mejores, hay técnicas empíricas.
- alinear las fotos aéreas, hacen falta trazas GPS (que aprendiste a grabar y subir a OSM).
- cada serie de fotos aéreas hay que alinearla con las trazas.
- faltando trazas, alinear con lo ya mapeado, ya presente en OSM.
- nunca debes grabar las trazas "magnéticas" pues estarías y volviendo a subir las calles ya presentes.

la fuente de los nombres sigue siendo el gran misterio.

si tienes modo de contactar a las inmobiliarias y empresas de construcción de urbanizaciones, a ellos puedes pedir permiso, a nombre de OSM, para que podamos "warpear" sus planes. el derecho de autor y la prohibición de la copia son conceptos que aplican a cualquier obra: si haces algo, tienes derecho de autor; si no dices nada, nadie tiene permiso a copiar. entonces, las urbanizadoras hacen una urbanización, y son los autores del plan. si lo ponen en el público dominio, podemos copiarlo, si nos permiten copiarlo, podemos copiarlo, si no dicen nada, nadie tiene derecho sino ellos mismos. tan sencillo.

voy a quitarme de este hilo, y se lo dejo a los latinoamericanos, pues yo no creo haber entendido mucho de los comentarios de @alvarado2510.

**Comment by risturiz** [comment]
> Renunciare a mapillary, usare StreetComplety ya que me lo recomendaron, espero que me ayude para responder los cientos de correos que tengo pendientes

Aún cuando te recomendaron Streetcomplete para las fotos, no creo que sea el app mas idónea... Streetcomplete tiene un sistema para conectar las fotos con notas de osm[1]; esto causa que apenas cierren la nota entonces la foto desaparece... Yo recomendaría mejor un servicio federado como [Pixelfed](https://pixelfed.org/) o el mismo [Mastodon](https://joinmastodon.org/) para subir fotos donde tienes control de tus fotos, puedes usar algún servidor público o montar tu propia instancia y lo más importante que tienes los derechos sobre tus fotos.

>En el grupo que estoy de OSM, nos facilitaron el año pasado una herramienta "ispector", algo así, muy buen creo que es la que usa @mfrasca para detectar mis errores, allí encontré la cantidad de cosas que edite y que a la fechas están incompletas.
Por ejemplo descubrí que el numero de las casa va ligado en OSM con el nombre de la calle, por esos me detuve seguir editando casa con numero, hasta corregir todas las anteriores.
Por ejemplo tengo la foto de todas las casas del residencial "Quinta de La Riviera", pero no se las coloco, por que no tengo los nombre de las calles del residencial, ese residencial lo tengo pendiente, en ese punto, hasta tener la información completa y así llevarla a OSM.

Quizás te refieres a [OSM Inspector](https://wiki.openstreetmap.org/wiki/OSM_Inspector) ... Yo tengo la preferencia personal de ir editando y cada cierto tiempo corregir los errores ( muchas veces son errores heredados ), porque seguramente con la información que vas subiendo hacia OSM otras personas se animan a colaborar en el mapa.

Lo del offset de la imagen satelital pudiésemos revisarlo con Strava... O si estás en la zona y puedes realizar una traza GPS, con eso se puede alinear la imagen satelital y guarda ese cambio para otros mapeadores ( @angoca es experto e alineando imagen satelital )... No existe alguien con dron en Panamá que quiera colaborar con las imágenes? :-)

[1] https://github.com/streetcomplete/sc-photo-service
